### ISSUE TITLE
Fortran Compilation

### ISSUE THREAD

**Issue by theSundayProgrammer** [IanLinsdell/Raspberrypi#1]
Is there a way of cross compiling fortran  using these tools.

**Comment by IanLinsdell** [comment]
I'm not familiar with Fortran but the gcc compiler appears to indicate that its included:
https://gcc.gnu.org/onlinedocs/gfortran/GNU-Fortran-and-GCC.html#GNU-Fortran-and-GCC

Date: Wed, 11 Mar 2015 19:02:56 -0700

**Comment by theSundayProgrammer** [comment]
Well the compiler f951 is not there. When I tried to compile a .f90 file it came up with "fortran compiler not installed on this system"
Is there some document describing how to build the compiler on Cygwin. The compiler exists on Linux.

**Comment by IanLinsdell** [comment]
You could start with looking at 'http://crosstool-ng.org/'
It might just work out of the box as it looks like its been updated since I last used it.but in the old days, you often ended up having to manually update some scripts / source files to get it to fully work on windows/cygwin

Date: Thu, 12 Mar 2015 22:32:16 -0700

**Comment by theSundayProgrammer** [comment]
Thanks Ian. For now I managed to install Fortran on Raspberry Pi. I am sure I'll run out of resources to continue doing that on Pi. I hope to get back to this issue soon.
